---
- name: Setup Virtualhosts
  template: >
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/{{ item.hostname }}.conf
    owner=root
    group=root
    mode=0644
  with_items: apache_virtualhosts
  when: apache_virtualhosts|length > 0
  notify: restart apache

- name: Remove default virtualhosts
  file: >
    name={{ item }}
    state=absent
  with_items:
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-available/default-ssl.conf
    - /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Enable virtualhost
  shell: >
    a2ensite {{ item.hostname }}.conf
    creates=/etc/apache2/sites-enabled/{{ item.hostname }}.conf
  with_items: apache_virtualhosts
  when: apache_virtualhosts|length > 0
  notify: restart apache

